### ISSUE TITLE
RVM don't save path

### ISSUE THREAD

**Issue by HaTe87** [plamoni/SiriProxy#497] opened 2013-03-28 11:25 UTC
when i stop the server i always do
[[ -s "/etc/profile.d/rvm.sh" ]] && . "/etc/profile.d/rvm.sh"
to are able to start siriproxy again ....why?

**Comment by elvisimprsntr** [comment] 2013-04-14 04:44
perform the second step to all the path to the .bash_profile file.

Set the RVM path to be set up every time I log in
`echo '[[ -s "/etc/profile.d/rvm.sh" ]] && . "/etc/profile.d/rvm.sh" # Load RVM function' >> ~/.bash_profile`

**Comment by HaTe87** [comment] 2013-04-15 09:17
I do that serveral time, but if i close the terminal or when i reboot i need to reuse:
[[ -s "/etc/profile.d/rvm.sh" ]] && . "/etc/profile.d/rvm.sh"

**Comment by elvisimprsntr** [comment] 2013-04-15 09:28
Can you confirm the entry was added to the .bash_profile file?

**Comment by HaTe87** [comment] 2013-04-15 09:31
sure...i see 3 times [[ -s "/etc/profile.d/rvm.sh" ]] && . "/etc/profile.d/rvm.sh" # Load RVM function

**Comment by elvisimprsntr** [comment] 2013-04-15 09:44
First, remove the duplicates from the .bash_profile

Try manually running the .bash_profile. If it works the you are likely logging in using a terminal type that does not automatically run the .bash_profile file. 

Try adding the same entry to the .bashrc file.  

What host OS are your using? What method are you using to open a terminal window? Console, SSH, etc.

**Comment by HaTe87** [comment] 2013-04-15 09:55
yesterday i tried to delete the .bash_profile ande re-set the path but it's the same. i also edit the .bashrc ,but nothing work. 
i use that image http://sourceforge.net/projects/siriproxyrpi/
and to use the terminal i connect the RPI to a monitor. so i use the real machine

**Comment by elvisimprsntr** [comment] 2013-04-15 10:12
You are logging in directly.  The problem is the file is not getting called when you login using that method.  

Try using a SSH client to remotely login to the RPi from another computer. 

MacOS its included 
Linux apt-get install ssh
Windows use putty.exe - http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html

Are you using the console login?   Or opening a terminal/console window using the desktop? 

Elvis

**Comment by HaTe87** [comment] 2013-04-15 12:41
i'm using desktop mode and i have used winscp to connect and take the cert

**Comment by elvisimprsntr** [comment] 2013-04-15 12:59
what terminal application are you using to open a command line.   if you don't use the correct terminal window type, it will not source the .bash_profile file.  don't use a console window.  open a xterm session.   you should be able to figure it out from here.  

Elvis

On Apr 15, 2013, at 8:41 AM, HaTe87 notifications@github.com wrote:

i'm using desktop mode and i have used winscp to connect and take the cert

**Comment by elvisimprsntr** [comment] 2013-04-15 22:47
type `source .bash_profile` until I determine a more permanent fix for the Raspberry Pi SD card image that will support console logins.  I am going to close this issue since it is not specifically related to siriproxy itself.  I have updated the release notice accordingly.

**Closed as completed by elvisimprsntr** 2013-04-15 22:47 UTC
Labels: Installation or Setup Problem
