### ISSUE TITLE
Installing siri proxy on mountain lion os

### ISSUE THREAD

**Issue by paradajoseluis** [plamoni/SiriProxy#382] opened 2012-11-28 20:59 UTC
Iam having problems installing siri proxy on mountain lion i am using this codes. I am specialy having problem installing rvm i have try so many ways i havent sucedded. Little help with the codes please

1) bash < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/ binscripts/rvm-installer)
2) [[ -s "$home/.rvm/scripts/rvm" ]] && . “$home/.rvm/scripts/rvm”
3) [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session _as a function_
4) rvm install 1.9.3
5) rvm use 1.9.3 –-default
6) rvmsudo gem install rake bundler
7) rvmsudo rake install
8) mkdir ~/.siriproxy
9) cp ./config.example.yml ~/.siriproxy/config.yml CERTIFICATE INSTALLATION:
1) mkdir ca
2) cd ca
3) /System/Library/OpenSSL/misc/CA.pl -newca
4) /System/Library/OpenSSL/misc/CA.pl -newreq guzzoni.apple.com
5) /System/Library/OpenSSL/misc/CA.pl -sign
6) openssl rsa -in newkey.pem -out server.passless.key 7) cp newcert.pem server.passless.crt
8) mv server.passless.\* ../
These are the commands used in Part 2:
1) sudo port install dnsmasq
2) address=/guzzoni.apple.com/your-computer-IP
3) sudo dnsmasq
4) rvmsudo ./siriproxy bundle
5) rvmsudo ./siriproxy server

**Comment by plamoni** [comment] 2012-11-28 21:06
Can you please provide more information such as:
1. What errors (if any) are you seeing?
2. What steps (if any) are failing?
3. What specific behavior you're experiencing on the device?

etc.

**Comment by paradajoseluis** [comment] 2012-11-29 01:47
paradaserver:SiriProxy paradaserver$ rvm install ruby-1.9.3-p327

No binary rubies available for: downloads/ruby-1.9.3-p327.
Continuing with compilation. Please read 'rvm mount' to get more information on binary rubies.
Fetching yaml-0.1.4.tar.gz to /Users/paradaserver/.rvm/archives
Extracting yaml to /Users/paradaserver/.rvm/src/yaml-0.1.4
Configuring yaml in /Users/paradaserver/.rvm/src/yaml-0.1.4.
Error running './configure --prefix=/Users/paradaserver/.rvm/usr', please read /Users/paradaserver/.rvm/log/ruby-1.9.3-p327/yaml/configure.log
Compiling yaml in /Users/paradaserver/.rvm/src/yaml-0.1.4.
Error running 'make', please read /Users/paradaserver/.rvm/log/ruby-1.9.3-p327/yaml/make.log
Installing Ruby from source to: /Users/paradaserver/.rvm/rubies/ruby-1.9.3-p327, this may take a while depending on your cpu(s)...
ruby-1.9.3-p327 - #downloading ruby-1.9.3-p327, this may take a while depending on your connection...
ruby-1.9.3-p327 - #extracted to /Users/paradaserver/.rvm/src/ruby-1.9.3-p327 (already extracted)
ruby-1.9.3-p327 - #configuring
Error running './configure --enable-shared --disable-install-doc --prefix=/Users/paradaserver/.rvm/rubies/ruby-1.9.3-p327 --with-opt-dir=/Users/paradaserver/.rvm/usr', please read /Users/paradaserver/.rvm/log/ruby-1.9.3-p327/configure.log
There has been an error while running configure. Halting the installation.

paradaserver:SiriProxy paradaserver$ rvm install ruby-1.9.3

No binary rubies available for: downloads/ruby-1.9.3-p327.
Continuing with compilation. Please read 'rvm mount' to get more information on binary rubies.
Fetching yaml-0.1.4.tar.gz to /Users/paradaserver/.rvm/archives
Extracting yaml to /Users/paradaserver/.rvm/src/yaml-0.1.4
Configuring yaml in /Users/paradaserver/.rvm/src/yaml-0.1.4.
Error running './configure --prefix=/Users/paradaserver/.rvm/usr', please read /Users/paradaserver/.rvm/log/ruby-1.9.3-p327/yaml/configure.log
Compiling yaml in /Users/paradaserver/.rvm/src/yaml-0.1.4.
Error running 'make', please read /Users/paradaserver/.rvm/log/ruby-1.9.3-p327/yaml/make.log
Installing Ruby from source to: /Users/paradaserver/.rvm/rubies/ruby-1.9.3-p327, this may take a while depending on your cpu(s)...
ruby-1.9.3-p327 - #downloading ruby-1.9.3-p327, this may take a while depending on your connection...
ruby-1.9.3-p327 - #extracted to /Users/paradaserver/.rvm/src/ruby-1.9.3-p327 (already extracted)
ruby-1.9.3-p327 - #configuring
Error running './configure --enable-shared --disable-install-doc --prefix=/Users/paradaserver/.rvm/rubies/ruby-1.9.3-p327 --with-opt-dir=/Users/paradaserver/.rvm/usr', please read /Users/paradaserver/.rvm/log/ruby-1.9.3-p327/configure.log
There has been an error while running configure. Halting the installation.

paradaserver:SiriProxy paradaserver$ rvm install 1.9.3

No binary rubies available for: downloads/ruby-1.9.3-p327.
Continuing with compilation. Please read 'rvm mount' to get more information on binary rubies.
Fetching yaml-0.1.4.tar.gz to /Users/paradaserver/.rvm/archives
Extracting yaml to /Users/paradaserver/.rvm/src/yaml-0.1.4
Configuring yaml in /Users/paradaserver/.rvm/src/yaml-0.1.4.
Error running './configure --prefix=/Users/paradaserver/.rvm/usr', please read /Users/paradaserver/.rvm/log/ruby-1.9.3-p327/yaml/configure.log
Compiling yaml in /Users/paradaserver/.rvm/src/yaml-0.1.4.
Error running 'make', please read /Users/paradaserver/.rvm/log/ruby-1.9.3-p327/yaml/make.log
Installing Ruby from source to: /Users/paradaserver/.rvm/rubies/ruby-1.9.3-p327, this may take a while depending on your cpu(s)...
ruby-1.9.3-p327 - #downloading ruby-1.9.3-p327, this may take a while depending on your connection...
ruby-1.9.3-p327 - #extracted to /Users/paradaserver/.rvm/src/ruby-1.9.3-p327 (already extracted)
ruby-1.9.3-p327 - #configuring
Error running './configure --enable-shared --disable-install-doc --prefix=/Users/paradaserver/.rvm/rubies/ruby-1.9.3-p327 --with-opt-dir=/Users/paradaserver/.rvm/usr', please read /Users/paradaserver/.rvm/log/ruby-1.9.3-p327/configure.log
There has been an error while running configure. Halting the installation.

paradaserver:SiriProxy paradaserver$ rvm install 1.9.3 --with-gcc=clang

You requested building with 'clang' but it is not in your path.

this was a message that appear when i enter all the previous commands. after pressing enter it run and gave does previous errors.

Ruby (and needed base gems) for your selection will be installed shortly.
Before it happens, please read and execute the instructions below.
Please use a separate terminal to execute any additional commands.
Notes for Mac OS X 10.8.2, Xcode 4.5.2.
For JRuby: Install the JDK. See http://developer.apple.com/java/download/ # Current Java version "1.6.0_26"
For IronRuby: Install Mono >= 2.6
For Ruby 1.9.3: Install libksba # If using Homebrew, 'brew install libksba'
For Opal: Install Nodejs with NPM. See http://nodejs.org/download/
To use an RVM installed Ruby as default, instead of the system ruby:
rvm install 1.8.7 # installs patch 357: closest supported version
rvm system ; rvm gemset export system.gems ; rvm 1.8.7 ; rvm gemset import system.gems # migrate your gems
rvm alias create default 1.8.7
And reopen your terminal windows.
Xcode and gcc:

**Comment by Deanmv** [comment] 2012-12-04 12:15
Is not it not:

rvm install 1.9.3

Not:

rvm install ruby-1.9.3-p327

**Comment by paradajoseluis** [comment] 2012-12-20 07:22
I tried with all of this commands and all of them fail to install i only had this problem with mountain lion:
rvm install ruby-1.9.3-p327

rvm install 1.9.3

rvm install ruby-1.9.3

rvm install 1.9.3 --with-gcc=clang

**Comment by bgottsch** [comment] 2013-03-04 17:19
delete xcode (you could move it to an external hd) and all ruby stuff, install gcc for 10.7 and then try to install ruby. If the problem is not solved, fresh install 10.8. After the fresh install, install gcc then ruby then siriproxy then Xcode. I had the same problem.

**Comment by plamoni** [comment] 2013-03-04 18:03
You might try doing this for installing RVM:

```
curl -L https://get.rvm.io | bash -s stable --ruby
```

Then do `rvm install 1.9.3`

Though you can also try 2.0.0 if you're feeling daring. Might work better for you.

I'm working on instructions for installing SiriProxy from rubygems, which should make parts of this process easier.

-Pete

**Comment by elvisimprsntr** [comment] 2013-04-18 02:13
I'm going to close this one since Pete published new instructions for installing SP as a gem.

**Closed as completed by elvisimprsntr** 2013-04-18 02:13 UTC
Labels: Installation or Setup Problem
