### ISSUE TITLE
Weird error while starting siri proxy !

### ISSUE THREAD

**Issue by ritvik1512** [plamoni/SiriProxy#427] opened 2013-02-01 11:07 UTC
when i run siriproxy server on ubuntu 12.04 it first says siri proxy is running and then when i speak it into my iPad 3 errors start showing up and the the server ends error like this come up :
root@ubuntu:~/SiriProxy# siriproxy server
Starting SiriProxy on 192.168.0.102:443..
SiriProxy up and running.
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x97ef0a0 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x97eef88>, @zip_stream=#Zlib::Deflate:0x97eef74, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x9a6553c @manager=#<SiriProxy::PluginManager:0x97eeaec @plugins=[...]>>]
[Info - iPhone] Received Object: LoadAssistant
/usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:217:in `encode': "\x85" on UTF-8 (Encoding::InvalidByteSequenceError)
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:217:in`charset_convert'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:442:in `string_to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:48:in`to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `block in dict_to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in`map'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `dict_to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:243:in`to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `block in dict_to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in`map'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `dict_to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:243:in`to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:70:in `to_str'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFPropertyList.rb:363:in`to_str'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFPropertyList.rb:398:in `to_plist'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:150:in`inject_object_to_output_stream'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:90:in `process_compressed_data'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:58:in`receive_binary_data'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/em/protocols/linetext2.rb:94:in `receive_data'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run_machine'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy.rb:16:in`initialize'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in `new'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in`start_server'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:85:in `run_server'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:37:in`initialize'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/bin/siriproxy:6:in `new'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/bin/siriproxy:6:in`<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/siriproxy:23:in `load'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/siriproxy:23:in`<main>'

and then it ends please help !!!!

**Comment by Deanmv** [comment] 2013-02-01 11:30
Duplicate of #389

**Comment by ritvik1512** [comment] 2013-02-01 15:10
But could you please explain the possible reasons ? How can I update the cfpropertylist ? Please any help will be highly appreciated !

**Comment by Deanmv** [comment] 2013-02-01 17:10
You need to downgrade it from 2.2.0 to 2.1.2. Run `gem install CFPropertyList -v 2.1.2` and then do the following:

 Change into the SiriProxy directory
- run: "sudo vi siriproxy.gemspec"
- Replace the line approx 4 from bottom which contains "CFPropertyList"
  with the below:
  s.add_runtime_dependency('CFPropertyList', '2.1.2')
- stop the server
- run: "siriproxy update ."
- start the server

**Comment by ritvik1512** [comment] 2013-02-01 17:21
now after completing your intructions i see this :
Starting SiriProxy on 0.0.0.0:443..
SiriProxy up and running.
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x9115888 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x91157c0>, @zip_stream=#Zlib::Deflate:0x91157ac, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x873ac28 @manager=#<SiriProxy::PluginManager:0x9115590 @plugins=[...]>>]
[Info - iPhone] Received Object: LoadAssistant
/usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:217:in `encode': "\x85" on UTF-8 (Encoding::InvalidByteSequenceError)
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:217:in`charset_convert'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:442:in `string_to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:48:in`to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `block in dict_to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in`map'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `dict_to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:243:in`to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `block in dict_to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in`map'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `dict_to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:243:in`to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:70:in `to_str'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFPropertyList.rb:363:in`to_str'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFPropertyList.rb:398:in `to_plist'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:150:in`inject_object_to_output_stream'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:90:in `process_compressed_data'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:58:in`receive_binary_data'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/em/protocols/linetext2.rb:94:in `receive_data'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run_machine'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy.rb:16:in`initialize'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in `new'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in`start_server'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:85:in `run_server'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:37:in`initialize'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/bin/siriproxy:6:in `new'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/bin/siriproxy:6:in`<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/siriproxy:23:in `load'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/siriproxy:23:in`<main>'

now what ??

**Comment by laxman01** [comment] 2013-02-01 17:55
It says your IP address is 0.0.0.0 , so go into .siriproxy/config.yml and change the 0.0.0.0 to your IP address

**Comment by Deanmv** [comment] 2013-02-02 10:29
That and you still have `(Encoding::InvalidByteSequenceError)` so those lines didn't work correctly.

**Comment by ritvik1512** [comment] 2013-02-02 10:43
i have trying changing the ip but still  no luck what next ????

**Comment by laxman01** [comment] 2013-02-02 14:49
I would recommend downloading 
http://rubyforge.org/frs/download.php/76604/CFPropertyList-2.1.2.zip
Then placing the contents of that folder in the CFPropertylist 2.2.0 folder located in
/Users/your username/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0

**Comment by laxman01** [comment] 2013-02-02 14:53
That would also mean you would have to run 

Change into the SiriProxy directory

run: "sudo vi siriproxy.gemspec"
Replace the line approx 4 from bottom which contains "CFPropertyList"
with the below:
s.add_runtime_dependency('CFPropertyList', '2.2.0')

stop the server

run: "siriproxy update ."

start the server

**Comment by ritvik1512** [comment] 2013-02-03 16:04
Siri Porxy is up and running ! Sweeet !
everybody @Deanmv and @laxman01 thank you a lot !!!
now moving on to plugins !

**Closed as completed** 2013-02-09 21:35 UTC
