### ISSUE TITLE
InvalidByteSequenceError

### ISSUE THREAD

**Issue by harlando** [plamoni/SiriProxy#389] opened 2012-12-16 14:53 UTC
I followed all the steps. Got siriproxy running. When I try to connect for, the iPhone I see the connection attempt from the Ubuntu terminal but then siriproxy stops with an error. I am running Ubuntu on a VM in Parallels on A Mac. I'm connecting using an iPhone 5

SiriProxy up and running.
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x9f6cc74 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x9f6cbc0>, @zip_stream=#Zlib::Deflate:0x9f6cb98, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x9906920 @manager=#<SiriProxy::PluginManager:0x9f6c940 @plugins=[...]>>]
[Info - iPhone] Received Object: LoadAssistant
/home/user/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:217:in `encode': "\xAB" on UTF-8 (Encoding::InvalidByteSequenceError)
    from /home/user/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:217:in`charset_convert'
    from /home/user/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:442:in `string_to_binary'
    from /home/user/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:48:in`to_binary'
    from /home/user/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `block in dict_to_binary'
    from /home/user/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in`map'
    from /home/user/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `dict_to_binary'
    from /home/user/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:243:in`to_binary'
    from /home/user/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `block in dict_to_binary'
    from /home/user/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in`map'
    from /home/user/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `dict_to_binary'
    from /home/user/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:243:in`to_binary'
    from /home/user/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:70:in `to_str'
    from /home/user/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFPropertyList.rb:363:in`to_str'
    from /home/user/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFPropertyList.rb:398:in `to_plist'
    from /home/user/SiriProxy/lib/siriproxy/connection.rb:150:in`inject_object_to_output_stream'
    from /home/user/SiriProxy/lib/siriproxy/connection.rb:90:in `process_compressed_data'
    from /home/user/SiriProxy/lib/siriproxy/connection.rb:58:in`receive_binary_data'
    from /home/user/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/eventmachine-1.0.0/lib/em/protocols/linetext2.rb:94:in `receive_data'
    from /home/user/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run_machine'
    from /home/user/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
    from /home/user/SiriProxy/lib/siriproxy.rb:16:in`initialize'
    from /home/user/SiriProxy/lib/siriproxy/command_line.rb:96:in `new'
    from /home/user/SiriProxy/lib/siriproxy/command_line.rb:96:in`start_server'
    from /home/user/SiriProxy/lib/siriproxy/command_line.rb:85:in `run_server'
    from /home/user/SiriProxy/lib/siriproxy/command_line.rb:37:in`initialize'
    from /home/user/SiriProxy/bin/siriproxy:6:in `new'
    from /home/user/SiriProxy/bin/siriproxy:6:in`<top (required)>'
    from /home/user/.rvm/gems/ruby-1.9.3-p327@SiriProxy/bin/siriproxy:19:in `load'
    from /home/user/.rvm/gems/ruby-1.9.3-p327@SiriProxy/bin/siriproxy:19:in`<main>'
    from /home/user/.rvm/gems/ruby-1.9.3-p327@SiriProxy/bin/ruby_noexec_wrapper:14:in `eval'
    from /home/user/.rvm/gems/ruby-1.9.3-p327@SiriProxy/bin/ruby_noexec_wrapper:14:in`<main>'
user@ubuntu:~/SiriProxy$

**Comment by jmmmm4** [comment] 2012-12-16 21:38
https://github.com/jimmykane/The-Three-Little-Pigs-Siri-Proxy/issues/389

**Comment by harlando** [comment] 2012-12-16 22:25
Hi, thanks for the link.  I just read the thread in The-Three-Little-Pigs. I'm new to this stuff, does the link provide a solution? 

Thanks :-)

**Comment by jmmmm4** [comment] 2012-12-16 22:32
- Change into the SiriProxy directory
- run: "sudo vi siriproxy.gemspec"
- Replace the line approx 4 from bottom which contains "CFPropertyList"
  with the below:
  s.add_runtime_dependency('CFPropertyList', '2.1.2')
- stop the server
- run: "siriproxy update ."
- start the server

Done :-)

Sent from my iPad

On 16 Dec 2012, at 22:25, harlando notifications@github.com wrote:

Hi, thanks for the link. I just read the thread in The-Three-Little-Pigs.
I'm new to this stuff, does the link provide a solution?

Thanks :-)

—
Reply to this email directly or view it on
GitHubhttps://github.com/plamoni/SiriProxy/issues/389#issuecomment-11423899.

**Comment by harlando** [comment] 2012-12-16 22:36
Awesome!!!!  Can't wait to get home and try it. That's super nice of you to help out.

**Comment by jmmmm4** [comment] 2012-12-16 22:50
No problem - I had the same issues today trying to get it working! It's
working properly now :-)

Sent from my iPhone

On 16 Dec 2012, at 22:36, harlando notifications@github.com wrote:

Awesome!!!! Can't wait to get home and try it. That's super nice of you to
help out.

—
Reply to this email directly or view it on
GitHubhttps://github.com/plamoni/SiriProxy/issues/389#issuecomment-11424065.

**Comment by harlando** [comment] 2012-12-16 23:37
It worked!!!!!!! I'm so excited, thanks! Now onto plugins......

**Comment by elmurato** [comment] 2012-12-17 10:24
I can confirm that the workaround works (siriproxy 0.3.2 iphone 5 ios 6.0.1), Should be fixed in the installer though. I think this issue can be closed now.

**Comment by flash66** [comment] 2012-12-21 10:30
Just replace the lib folder located in .rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/CFPropertyList-2.2.0 with the lib folder located in your earlier CFPropertyList-2._._ that worked. Forget about the line change and just leave it "CFPropertyList" in siriproxy.gemspec
If the line change didn't work for you, then this will :)

**Comment by Deanmv** [comment] 2012-12-21 11:52
The above worked for me but my CFPropertyList 2.1.2 was deleted when 2.2.0 was installed I think, (or maybe anyone that installed after 2.2.0 was released on 14th Dec).  I had to run

gem install CFPropertyList -v 2.1.2

and apply the patch to the gemspec file for it to work again.

**Comment by mpdifran** [comment] 2012-12-31 01:08
I've installed v 2.1.2 of CFPropertyList, and edited the gemspec to use 2.1.2, but I still get the error. Does the 2.1.2 folder need to be in the same location as the 2.2.0 fodler? ie in .rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/ ?

EDIT I've copied the contents of 2.1.2 into the folder in @SiriProxy named 2.2.0, it seems to be the only way I could get it to work...

**Comment by plamoni** [comment] 2013-02-09 21:02
Possible fix here: 4a1ba082fdd55ea2bbca5f0d04aa5c095ea46459

I can't test because I'm about 1700 miles from home at the moment. However, this should work to fix the issue.

Try it out using `siriproxy update --branch cfpropertylist-fix`

I'll test it when I get home and if it's fine I'll merge into master.

Sorry for the trouble, I should have fixed this one a while ago.

**Comment by ciryon** [comment] 2013-02-10 21:41
I can confirm that the fix works. Thanks!

**Comment by plamoni** [comment] 2013-02-11 00:22
I can also confirm it works (or at least doesn't break anything major). I'm going to merge to master. Thanks for the second look, @ciryon

**Closed as completed** 2013-02-22 19:04 UTC
