### ISSUE TITLE
Wreid proxy error when  my ipod connects to siri

### ISSUE THREAD

**Issue by mantas7776** [plamoni/SiriProxy#249] opened 2012-01-02 19:10 UTC
mantas@mantas-VirtualBox:~/SiriProxy$ rvmsudo siriproxy server
Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x935b73c @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x935b660>, @zip_stream=#Zlib::Deflate:0x935b64c, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x8fdb8c8 @manager=#<SiriProxy::PluginManager:0x935b41c @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x8fdb79c @signature=4, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x8fdb648>, @zip_stream=#Zlib::Deflate:0x8fdb620, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x903fa44 @manager=#<SiriProxy::PluginManager:0x904019c @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x903f904 @signature=5, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x903f7b0>, @zip_stream=#Zlib::Deflate:0x903f788, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x903e978 @manager=#<SiriProxy::PluginManager:0x903f2d8 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x903e838 @signature=6, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x903e644>, @zip_stream=#Zlib::Deflate:0x903e5f4, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x903d974 @manager=#<SiriProxy::PluginManager:0x903e0f4 @plugins=[...]>>]

when i try to turn on siri it tells server down. but on terminal i get this. I use ipod 3g. Certs installing/uninstalling not help. Tried regenerating certs still not help. My imessage mantas7776@gmail.com .

EDIT1:lol found issue i wrote suzzoni.apple.com :D
EDIT2: still  getting same
EDIT3: done > rake install > siriproxy bundle > started server > still same, restarting vm not works

**Comment by gotnull** [comment] 2012-01-02 23:29
Are you using your iPhone 4S and your iPod to initiate Siri? I didn't think Siri was available on anything other than an iPhone 4S.

**Comment by FineTralfazz** [comment] 2012-01-02 23:49
Dupe of #239.

**Comment by j-mcnally** [comment] 2012-01-02 23:51
U still need an iPhone 4S. If your using one of the Caching forks, the iphone 4S still needs connect once a day to update all the tokens.

**Comment by mantas7776** [comment] 2012-01-03 07:51
guys its spire.

**Comment by j-mcnally** [comment] 2012-01-03 07:54
It doesn't matter, to use spire, via siriproxy you need to have a 4S' tokens. You can copy them in manually once a day or use one of the caching branches. But you still need a 4S readily available to generate the tokens.

**Comment by mantas7776** [comment] 2012-01-03 08:00
that sux :(

**Comment by j-mcnally** [comment] 2012-01-03 08:04
hold out hope, i hear siri may come to all IOS 5 devices. Also don't get desperate and pay for a siriproxy. From what I understand they are horribly unreliable, your better off just burning the money as a heat source ;)

**Comment by FineTralfazz** [comment] 2012-01-03 08:55
Siri won't be coming to anything which is currently released, as it's the main selling point of the 4S. Also SiriProxy is pretty darn reliable once you manage to actually get it working, though I wouldn't recommend using a paid service either.

**Comment by j-mcnally** [comment] 2012-01-03 08:57
Apple release an internal beta of Siri on Non-4s devices: http://www.jailbreaknation.com/apple-testing-siri-on-devices-other-than-the-iphone-4s-exclusive

**Comment by FineTralfazz** [comment] 2012-01-03 09:01
That doesn't mean anything.

**Comment by SilenceFictionxD** [comment] 2012-01-04 16:45
@Salax- Is it?
I think it means a lot. Apple has enough money and reputation and I think the honesty of Apple is great enough, I think we can expect Apple to release Siri to older iDevices.

**Comment by thecodingdude** [comment] 2012-01-04 18:01
I have the exact same problem. I've tried lots of stuff but nothing ever seems to work. HOWEVER when I go to:

https://[ip]:443 I see a message about a 4S not connected. I am confused as to what to do next...

**Comment by bowtakwah** [comment] 2012-01-09 12:32
@j-mcnally I thought Apple generates the token when you send a 4S key to them. From there, you can store and use the token until it expires.

**Comment by bowtakwah** [comment] 2012-01-11 12:57
@rakusu Yes. I want to know if you can obtain a new token by passing the 4S key without the actual 4s phone. I believe you can store the 4s key using westbaer.

**Comment by j-mcnally** [comment] 2012-01-12 18:48
@rakusu @bowtakwah, no you will always need the phone. I believe "extracting a key" if possible, would defiantly be illegal. There is a difference between replaying and forging.

**Comment by gotnull** [comment] 2012-01-12 22:47
@bowtakwah Oh, I now understand what you're after. That's illegal. I wouldn't condone that sort've activity, at all.

**Closed as completed** 2013-03-11 17:01 UTC
