### ISSUE TITLE
SiriProxy quits as soon as mic is pressed 

### ISSUE THREAD

**Issue by gavros** [plamoni/SiriProxy#391] opened 2012-12-18 04:27 UTC
Hey guys,

Recently I picked up a Raspberry Pi and decided to play around with siriproxy (well for the obvious reasons) ;) I've done a clean install (latest version of raspbian wheezy). The problem I'm having is that as soon as I run siriproxy and I hit the mic it quits. I've tried this twice but I just cant seem to figure out what the problem is (I did notice that encoding error in the beginning not sure if that is the problem - using US-ENG UTF-8). 

Any suggestions would be greatly appreciated and thanks in advance :) 
# Below is the log:

root@raspberrypi:~/SiriProxy# siriproxy serverStarting SiriProxy on port 443..
SiriProxy up and running.
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0xa28d48 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0xa28b08>, @zip_stream=#Zlib::Deflate:0xa28af0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0xdead10 @manager=#<SiriProxy::PluginManager:0xa28538 @plugins=[...]>>]
[Info - iPhone] Received Object: LoadAssistant
/usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:217:in `encode': "\x85" on UTF-8 (Encoding::InvalidByteSequenceError)
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:217:in`charset_convert'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:442:in `string_to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:48:in`to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `block in dict_to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in`map'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `dict_to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:243:in`to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `block in dict_to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in`map'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `dict_to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:243:in`to_binary'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:70:in `to_str'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFPropertyList.rb:363:in`to_str'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFPropertyList.rb:398:in `to_plist'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:150:in`inject_object_to_output_stream'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:90:in `process_compressed_data'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:58:in`receive_binary_data'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/eventmachine-1.0.0/lib/em/protocols/linetext2.rb:94:in `receive_data'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run_machine'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy.rb:16:in`initialize'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in `new'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in`start_server'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:85:in `run_server'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:37:in`initialize'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/bin/siriproxy:6:in `new'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/bin/siriproxy:6:in`<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/bin/siriproxy:23:in `load'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/bin/siriproxy:23:in`<main>'
root@raspberrypi:~/SiriProxy#

**Comment by taschik** [comment] 2012-12-18 08:57
same here! First I thought it might be related to the Umlaut issue I read about but than I switched to English Siri language and the error is still there. I installed it on Raspberry Pi, too.

**Comment by Deanmv** [comment] 2012-12-18 10:14
Looks like a duplicate of #389  ?

**Comment by ghost** [comment] 2012-12-18 11:51
I suffered the same issue in #390 - the fix in #389 worked for me.

**Comment by taschik** [comment] 2012-12-18 12:39
I can confirm that #389 works for me.

**Comment by gavros** [comment] 2012-12-19 01:56
Thanks for the quick response everyone. Unfortunately the fix in #389 did not work for me. :( 
Still getting the same error. Tested with an iphone 4S (ios 5.0.1) & iphone 5 6.0.1. No joy. Any suggestions?

**Comment by markhellier** [comment] 2012-12-21 06:17
No luck with the fix in #389 for me either. my log is very smilar, different install paths. iPhone5 ios6.0.2

**Comment by sjamthe** [comment] 2012-12-21 08:29
Didnt work for be wit iphone 5 ios 6.0.2 or ipad 3 (new) ios 6.0.1
ipad error is below

Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x000000015e0690 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x000000015e8610>, @zip_stream=#Zlib::Deflate:0x000000015e6e78, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000001a2da68 @manager=#<SiriProxy::PluginManager:0x000000016beeb8 @plugins=[...]>>]
[Info - iPhone] Received Object: LoadAssistant
/usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:217:in `encode': "\x81" on UTF-8 (Encoding::InvalidByteSequenceError)
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:217:in`charset_convert'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:442:in `string_to_binary'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:48:in`to_binary'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `block in dict_to_binary'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in`map'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `dict_to_binary'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:243:in`to_binary'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `block in dict_to_binary'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in`map'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `dict_to_binary'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:243:in`to_binary'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:70:in `to_str'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFPropertyList.rb:363:in`to_str'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFPropertyList.rb:398:in `to_plist'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:150:in`inject_object_to_output_stream'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:90:in `process_compressed_data'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:58:in`receive_binary_data'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/eventmachine-1.0.0/lib/em/protocols/linetext2.rb:94:in `receive_data'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run_machine'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy.rb:16:in`initialize'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in `new'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in`start_server'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:85:in `run_server'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:37:in`initialize'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/bin/siriproxy:6:in `new'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/bin/siriproxy:6:in`<top (required)>'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/bin/siriproxy:23:in `load'
        from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/bin/siriproxy:23:in`<main>'

**Comment by ghost** [comment] 2012-12-21 09:09
Did you do a build after modifying the gemspec?

**Comment by sjamthe** [comment] 2012-12-21 15:32
Rebuilding fixed the issue. Thanks a lot.
Great work 

Regards
Shirish

**Comment by gavros** [comment] 2012-12-22 04:48
Ok I think I figured it out. Here is what I did to get it work:
- Change into the SiriProxy directory 
- run: "sudo vi siriproxy.gemspec" 
- Replace the line approx 4 from bottom which contains "CFPropertyList" with the below: s.add_runtime_dependency('CFPropertyList', '2.1.2') 
- stop the server 
- run > siriproxy update
- after that do a > rake install 
- start the server

Thanks everyone :)

**Comment by ghost** [comment] 2012-12-22 07:46
You need to do an rvmsudo ./siriproxy build like you did when you first installed it.

**Comment by plamoni** [comment] 2013-02-22 18:54
This has been fixed on master. Do a `siriproxy update` to resolve the problem.

**Closed as completed by plamoni** 2013-02-22 18:54 UTC
