### ISSUE TITLE
siriproxy says up and running in terminal but once i activate it on my device it crashes 

### ISSUE THREAD

**Issue by venom420x** [plamoni/SiriProxy#420] opened 2013-01-28 09:22 UTC
mac osx 10.7 error log in terminal 

venoms-imac:~ venom$ rvmsudo siriproxy server
Warning: can not check `/etc/sudoers` for `secure_path`, falling back to call via `/usr/bin/env`, this breaks rules from `/etc/sudoers`. export rvmsudo_secure_path=1 to avoid the warning.Password:
Starting SiriProxy on 0.0.0.0:443..
SiriProxy up and running.
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007fe2d351c738 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007fe2d351c350>, @zip_stream=#Zlib::Deflate:0x007fe2d351c288, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007fe2d3652a30 @manager=#<SiriProxy::PluginManager:0x007fe2d351bcc0 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007fe2d36525d0 @signature=5, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007fe2d3652468>, @zip_stream=#Zlib::Deflate:0x007fe2d3652440, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007fe2d3669668 @manager=#<SiriProxy::PluginManager:0x007fe2d3652058 @plugins=[...]>>]
[Info - iPhone] Received Object: LoadAssistant
/Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:217:in `encode': "\xD9" followed by "\xF1" on UTF-8 (Encoding::InvalidByteSequenceError)
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:217:in`charset_convert'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:442:in `string_to_binary'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:48:in`to_binary'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `block in dict_to_binary'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in`map'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `dict_to_binary'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:243:in`to_binary'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `block in dict_to_binary'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in`map'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `dict_to_binary'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:243:in`to_binary'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:70:in `to_str'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/CFPropertyList-2.2.0/lib/rbCFPropertyList.rb:363:in`to_str'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/CFPropertyList-2.2.0/lib/rbCFPropertyList.rb:398:in `to_plist'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:150:in`inject_object_to_output_stream'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:90:in `process_compressed_data'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:58:in`receive_binary_data'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/eventmachine-1.0.0/lib/em/protocols/linetext2.rb:94:in `receive_data'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run_machine'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/siriproxy-0.3.2/lib/siriproxy.rb:16:in`initialize'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in `new'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in`start_server'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:85:in `run_server'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:37:in`initialize'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/siriproxy-0.3.2/bin/siriproxy:6:in `new'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/siriproxy-0.3.2/bin/siriproxy:6:in`<top (required)>'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/bin/siriproxy:19:in `load'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/bin/siriproxy:19:in`<main>'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/bin/ruby_noexec_wrapper:14:in`<main>'
venoms-imac:~ venom$

**Comment by Deanmv** [comment] 2013-01-28 11:39
Duplicate of #389

**Comment by venom420x** [comment] 2013-01-28 20:25
Not a duplicate. I've read that post over and over again. The Solution didnt fix anything.

**Comment by laxman01** [comment] 2013-01-28 20:31
First off it says your IP is 0.0.0.0 
Witch it impossible. To fix that go to config.yml in the .siriproxy directory and at the top of the file change the 0.0.0.0 to your IP address

**Comment by laxman01** [comment] 2013-01-28 20:41
Then after you do that repost the output when you run "rvmsudo SiriProxy server"

**Comment by Deanmv** [comment] 2013-01-28 20:50
`Encoding::InvalidByteSequenceError` It is because you have CFProperlyList 2.2.0 and not 2.1.2.  You need to downgrade back to 2.1.2 or put the 2.1.2 files in the 2.2.0 folder and you don't "have" to set an IP as @laxman01 has said, it will just start the server on the local machine with the IP of that machine.  Not sure where 0.0.0.0 has come from?  The top of your config.yml file should just have your port, log level and then the plugins.

**Comment by laxman01** [comment] 2013-01-28 20:54
I would recommend downloading 
http://rubyforge.org/frs/download.php/76604/CFPropertyList-2.1.2.zip
Then placing the contents of that folder in the CFPropertylist 2.2.0 folder

**Comment by laxman01** [comment] 2013-01-28 21:13
@Deanmv 
Actually there has been a new update where you can configure it to listen to one IP, but you do have to set your IP at the top of config.yml

**Comment by venom420x** [comment] 2013-01-28 21:16
ok so i fixed the CFProperty problem now when i do rvmsudo siriproxy server it starts and says its running. when i press the button on my phone nothing at all happens.

**Comment by laxman01** [comment] 2013-01-28 21:18
Does it still say 
Starting SiriProxy on 0.0.0.0:443..

**Comment by venom420x** [comment] 2013-01-28 21:18
and i dont know if this is relevant but when i fixed the cfproperty list and ran the proxy it worked but it gave me a zlib:the host was freed prematurely error then i remember i had this error before and it was a dnsmasq problem so i reinstalled dnsmasq. and now im just stuck

**Comment by venom420x** [comment] 2013-01-28 21:18
no

**Comment by venom420x** [comment] 2013-01-28 21:19
venoms-iMac:~ venom$ rvmsudo siriproxy server
Warning: can not check `/etc/sudoers` for `secure_path`, falling back to call via `/usr/bin/env`, this breaks rules from `/etc/sudoers`. export rvmsudo_secure_path=1 to avoid the warning.Starting SiriProxy on 192.168.1.134:443..
SiriProxy up and running.

**Comment by venom420x** [comment] 2013-01-28 21:20
venoms-iMac:~ venom$ sudo dnsmasq
Password:

dnsmasq: failed to create listening socket for 192.168.1.134: Address already in use

**Comment by laxman01** [comment] 2013-01-28 21:20
And just to make sure... You have that same IP address set up on your phone in the DNS field on your iPhone

**Comment by venom420x** [comment] 2013-01-28 21:21
What do you mean? Like go into my phones wifi settings set up with a manual dhcp? and for the dns server put my computers ip?

**Comment by venom420x** [comment] 2013-01-28 21:22
Sorry new to this stuff. funny thing is i had this working once before. Then my hard drive got wiped. -_-

**Comment by laxman01** [comment] 2013-01-28 21:23
yes and same thing happened to me to as well everything working fine then computer got wiped.

also run
sudo lsof -i :443 | grep LISTEN
and tell me the output

**Comment by Deanmv** [comment] 2013-01-28 21:30
@laxman01 sorry wasn't aware of that update. Normally when mine won't respond i `sudo killall dnsmasq` then `sudo dnsmasq` again to get it started and normally it works. Also @venom420x run `export rvmsudo_secure_path=1` to get rid of that warning you have.

**Comment by venom420x** [comment] 2013-01-28 21:33
Thanks for that tip Deanmv and Thanks To both of you. i replaced the files in the CFProperty 2.2.0 folder with the files from 2.1.2. Then i forgot that the last time i ran into the zlib error it was because i didnt have my computers dns set to something else (like googles public 8.8.8.8) after that i restarted just to be on the safe side and now everything is working perfectly. Thank you!

**Comment by venom420x** [comment] 2013-01-28 21:34
The thing that was most frustrating was uninstalling homebrew to reinstall macports. that was a total pain.

**Comment by laxman01** [comment] 2013-01-28 21:34
Im glad we could help and good luck with plugins now

**Closed as completed by laxman01** 2013-01-28 21:34 UTC
